# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

export PS1="\n\[$(tput sgr0)\]\[\033[38;5;46m\][\t]\[$(tput sgr0)\] \[$(tput sgr0)\]\[\033[38;5;39m\]\w\[$(tput sgr0)\]\n\[$(tput sgr0)\]\[\033[38;5;210m\]\$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/')\[$(tput sgr0)\]\[\033[38;5;166m\]\\$\[$(tput sgr0)\] \[$(tput sgr0)\]"

export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

export CLASSPATH=".:/usr/local/lib/antlr-4.11.1-complete.jar:$CLASSPATH"
function pyantlr() {
    antlr4 -Dlanguage=Python3 "$@"
}

function get-ip() {
  dig +short myip.opendns.com @resolver1.opendns.com
}

complete -C '$(which aws_completer)' aws

# BEGIN SNIPPET: Platform.sh CLI configuration
# HOME=${HOME:-'/home/lousydropout'}
# export PATH="$HOME/"'.platformsh/bin':"$PATH"
# if [ -f "$HOME/"'.platformsh/shell-config.rc' ]; then . "$HOME/"'.platformsh/shell-config.rc'; fi # END SNIPPET


export PATH=$HOME/.bin:$PATH


# autocompletion for doctl
source <(doctl completion bash)


if [[ $(type -t compopt) = "builtin" ]]; then
    complete -o default -F __start_k3d k3d
else
    complete -o default -o nospace -F __start_k3d k3d
fi

# ex: ts=4 sw=4 et filetype=sh

complete -C /usr/bin/terraform terraform
###-begin-cdktf-completions-###
#
# yargs command completion script
#
# Installation: cdktf completion >> ~/.bashrc
#    or cdktf completion >> ~/.bash_profile on OSX.
#
_cdktf_yargs_completions()
{
    local cur_word args type_list

    cur_word="${COMP_WORDS[COMP_CWORD]}"
    args=("${COMP_WORDS[@]}")

    # ask yargs to generate completions.
    type_list=$(cdktf --get-yargs-completions "${args[@]}")

    COMPREPLY=( $(compgen -W "${type_list}" -- ${cur_word}) )

    # if no match was found, fall back to filename completion
    if [ ${#COMPREPLY[@]} -eq 0 ]; then
      COMPREPLY=()
    fi

    return 0
}
complete -o bashdefault -o default -F _cdktf_yargs_completions cdktf
###-end-cdktf-completions-###

#### -- azure env vars
ARM_DISPLAY_NAME="azure-cli-2023-02-08-19-43-30"
ARM_CLIENT_ID="f4ef2bac-f1d2-4898-9c64-8e0931172a86"
ARM_CLIENT_SECRET="<key removed>"
ARM_SUBSCRIPTION_ID="82218322-f18f-4eae-bcb3-f100f34db494"
ARM_TENANT_ID="c79cd323-b85f-4f31-89e5-885973962296"
###

# export PATH="$HOME/.avm/bin:$HOME/.local/share/solana/install/active_release/bin:/home/lousydropout/.zokrates/bin:$PATH"
# source ~/.solana_autocomplete.sh


function atest() {
    anchor test --skip-local-validator
}





function to-cbz() {
  rename "s/ /_/g" * && for f in *; do zip -r $f.cbz $f; rm -rf $f; rename "s/_/ /g" *.cbz; done
}


export OPENAI_API_KEY="<key removed>"
export LANGCHAIN_API_KEY="<key removed>"
export REPLICATE_API_TOKEN="<key removed>"

export PATH="$HOME/.foundry/bin:$HOME/.avalanchego:$HOME/.movement/bin:/home/linuxbrew/.linuxbrew/bin:/usr/local/go/bin:$HOME/bin:$HOME/go/bin:$BUN_INSTALL/bin:$HOME/.config/emacs/bin:$PATH"

alias glow="glow -lt"
alias wezterm='flatpak run org.wezfurlong.wezterm'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

nvm alias default lts/*

# opencode
export PATH=/home/lousydropout/.opencode/bin:$PATH

# Claude Code file protection wrapper
restricted-claude() {
  local config="$HOME/.config/restricted-claude/patterns"
  local claude_bin

  claude_bin="$(which claude 2>/dev/null)"
  if [[ -z "$claude_bin" ]]; then
    echo "Error: claude not found in PATH" >&2
    return 1
  fi

  if [[ ! -f "$config" ]]; then
    echo "Warning: No patterns file at $config" >&2
  else
    echo "Protecting sensitive files..."
    while IFS= read -r pattern || [[ -n "$pattern" ]]; do
      [[ -z "$pattern" || "$pattern" == \#* ]] && continue
      find . -name "$pattern" -type f \
        -not -path '*/.git/*' \
        -not -path '*/.ssh/*' \
        -not -path '*/node_modules/*' \
        -not -path '*/.venv/*' \
        -not -path '*/venv/*' \
        -not -path '*/target/*' \
        -exec chmod -v 600 {} \;
    done < "$config"
  fi

  "$claude_bin" "$@"
}

alias claude="restricted-claude"

# WezTerm - send current directory for new tab support
__wezterm_osc7() {
  printf '\033]7;file://%s%s\033\\' "$HOSTNAME" "$PWD"
}
PROMPT_COMMAND="__wezterm_osc7${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
